external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

victron:
  uart_id: ${inverter_uartid}
  id: ${inverter_name}_${inverter_sufix}
  throttle: ${inverter_throttle}
  
sensor:
  - platform: victron
    victron_id: ${inverter_name}_${inverter_sufix}
    # update_interval: ${inverter_update_interval}
    charging_mode_id:
      name: ${name}_${inverter_name}_charging_mode_id_${inverter_sufix}
    error_code:
      name: ${name}_${inverter_name}_error_code_${inverter_sufix}
    ac_out_current:
      name: ${name}_${inverter_name}_ac_output_current_${inverter_sufix}
      id: ${inverter_name}_ac_output_current_${inverter_sufix}
    ac_out_voltage:
      name: ${name}_${inverter_name}_ac_out_voltage_${inverter_sufix}
      id: ${inverter_name}_ac_output_voltage_${inverter_sufix}
    yield_total:
      name: ${name}_${inverter_name}_yield_total_${inverter_sufix}
    yield_today:
      name: ${name}_${inverter_name}_yield_today_${inverter_sufix}
    max_power_today:
      name: ${name}_${inverter_name}_max_power_today_${inverter_sufix}
    yield_yesterday:
      name: ${name}_${inverter_name}_yield yesterday_${inverter_sufix}
    max_power_yesterday:
      name: ${name}_${inverter_name}_max_power_yesterday_${inverter_sufix}
    day_number:
      name: ${name}_${inverter_name}_day_number_${inverter_sufix}
    battery_current:
      name: ${name}_${inverter_name}_battery_current_${inverter_sufix}
    panel_power:
      name: ${name}_${inverter_name}_pv_power_${inverter_sufix}
      id: ${inverter_name}_pv_power_${inverter_sufix}
    battery_voltage:
      name: ${name}_${inverter_name}_battery_voltage_${inverter_sufix}
    panel_voltage:
      name: ${name}_${inverter_name}_pv_voltage_${inverter_sufix}
      id: ${inverter_name}_pv_voltage_${inverter_sufix}
    load_current:
      name: ${name}_${inverter_name}_load_current_${inverter_sufix}
    state_of_charge:
      name: ${name}_${inverter_name}_soc_${inverter_sufix}
    ac_out_apparent_power:
      name: ${name}_${inverter_name}_ac_output_apparent_power_${inverter_sufix}
      

  - platform: template
    name: ${name}_${inverter_name}_ac_output_active_power_${inverter_sufix}
    lambda: |-
       auto val = id(${inverter_name}_ac_output_voltage_${inverter_sufix}).state * id(${inverter_name}_ac_output_current_${inverter_sufix}).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${inverter_template_update}
    
  - platform: template
    name: ${name}_${inverter_name}_pv_current_${inverter_sufix}
    lambda: |-
       auto val = id(${inverter_name}_pv_power_${inverter_sufix}).state / id(${inverter_name}_pv_voltage_${inverter_sufix}).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${inverter_template_update}   

binary_sensor:
  - platform: victron
    victron_id: ${inverter_name}_${inverter_sufix}
    relay_state:
      name: ${name}_${inverter_name}_relay_state    
    
text_sensor:
  - platform: victron
    victron_id: ${inverter_name}_${inverter_sufix}
    device_type:
      name: ${name}_${inverter_name}_device_type_${inverter_sufix}
    serial_number:
      name: ${name}_${inverter_name}_serial_number_${inverter_sufix}
    firmware_version_24bit:
      name: ${name}_${inverter_name}_firmware_version_24bit_${inverter_sufix}
    charging_mode:
      name: ${name}_${inverter_name}_charging_mode_${inverter_sufix}
    error:
      name: ${name}_${inverter_name}_error_${inverter_sufix}
    device_mode:
      name: ${name}_${inverter_name}_device mode_${inverter_sufix}

  
