sensor:
  - platform: bme280_i2c
    temperature:
      name: ${name}_${environnemental_name}_temperature
      accuracy_decimals: 1
      oversampling: 16x
      id: ${environnemental_name}_temperature
    pressure:
      name: ${name}_${environnemental_name}_pression
      accuracy_decimals: 1
      id: ${environnemental_name}_pression
    humidity:
      name: ${name}_${environnemental_name}_humidite
      accuracy_decimals: 1
      id: ${environnemental_name}_humidite
    address: ${environnemental_address}
    update_interval: ${environnemental_update_interval}
    i2c_id: ${environnemental_i2c_bus}

# https://esphome.io/components/sensor/absolute_humidity.html?highlight=absolute_humidity
  - platform: absolute_humidity
    name: ${name}_${environnemental_name}_humidite_absolue
    id: ${environnemental_name}_humidite_absolue
    equation: Wobus #Tetens #Buck
    temperature: ${environnemental_name}_temperature
    humidity: ${environnemental_name}_humidite
