external_components:
  - source: github://KinDR007/VictronSmartShunt-ESPHOME@main
    refresh: 0s

victron_smart_shunt:
  uart_id: ${smartshunt_uart_id}
  
sensor:
  - platform: victron_smart_shunt
#    id: ${smartshunt_name}_${smartshunt_suffix}
    battery_voltage:
      name: ${name}_${smartshunt_name}_battery_voltage_${smartshunt_suffix}
      id: ${smartshunt_name}_battery_voltage_${smartshunt_suffix}
      accuracy_decimals: 2

    battery_current:
      name: ${name}_${smartshunt_name}_battery_current_${smartshunt_suffix}
      id: ${smartshunt_name}_battery_current_${smartshunt_suffix}
      accuracy_decimals: 2

    fw_version:
      name: ${name}_${smartshunt_name}_fw_version_${smartshunt_suffix}
      id: ${smartshunt_name}_fw_version_${smartshunt_suffix}

    pid:
      name: ${name}_${smartshunt_name}_pid_${smartshunt_suffix}
      id: ${smartshunt_name}_pid_${smartshunt_suffix}

    instantaneous_power:
      name: ${name}_${smartshunt_name}_instantaneous_power_${smartshunt_suffix}
      id: ${smartshunt_name}_instantaneous_power_${smartshunt_suffix}
      accuracy_decimals: 2

    time_to_go:
      name: ${name}_${smartshunt_name}_time_to_go_${smartshunt_suffix}
      id: ${smartshunt_name}_time_to_go_${smartshunt_suffix}

    consumed_amp_hours:
      name: ${name}_${smartshunt_name}_consumed_amp_hours_${smartshunt_suffix}
      id: ${smartshunt_name}_consumed_amp_hours_${smartshunt_suffix}
      unit_of_measurement: Ah
      accuracy_decimals: 2

    min_battery_voltage:
      name: ${name}_${smartshunt_name}_min_battery_voltage_${smartshunt_suffix}
      id: ${smartshunt_name}_min_battery_voltage_${smartshunt_suffix}
      accuracy_decimals: 2

    max_battery_voltage:
      name: ${name}_${smartshunt_name}_max_battery_voltage_${smartshunt_suffix}
      id: ${smartshunt_name}_max_battery_voltage_${smartshunt_suffix}
      accuracy_decimals: 2

    amount_of_charged:
      name: ${name}_${smartshunt_name}_amount_of_charged_${smartshunt_suffix}
      id: ${smartshunt_name}_amount_of_charged_${smartshunt_suffix}
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: 1

    bmv_alarm_text:
      name: ${name}_${smartshunt_name}_bmv_alarm_${smartshunt_suffix}
      id: ${smartshunt_name}_bmv_alarm_${smartshunt_suffix}

    bmv_text:
      name: ${name}_${smartshunt_name}_bmv_text_${smartshunt_suffix}
      id: ${smartshunt_name}_bmv_text_${smartshunt_suffix}

    last_full_charge:
      name: ${name}_${smartshunt_name}_last_full_charge_${smartshunt_suffix}
      id: ${smartshunt_name}_last_full_charge_${smartshunt_suffix}

    deepest_discharge:
      name: ${name}_${smartshunt_name}_deepest_discharge_${smartshunt_suffix}
      id: ${smartshunt_name}_deepest_discharge_${smartshunt_suffix}
      unit_of_measurement: Ah
      accuracy_decimals: 1

    last_discharge:
      name: ${name}_${smartshunt_name}_last_discharge_${smartshunt_suffix}
      id: ${smartshunt_name}_last_discharge_${smartshunt_suffix}
      unit_of_measurement: Ah
      accuracy_decimals: 1

    discharged_energy:
      name: ${name}_${smartshunt_name}_discharged_energy_${smartshunt_suffix}
      id: ${smartshunt_name}_discharged_energy_${smartshunt_suffix}
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: 1

    state_of_charge:
      name: ${name}_${smartshunt_name}_state_of_charge_${smartshunt_suffix}
      id: ${smartshunt_name}_state_of_charge_${smartshunt_suffix}
      