# Updated : 2026.06.16
# Version : 1.0.1
# GitHub  : https://github.com/Dackara/

esphome:
  devices:
    - id: ${powermeter_name}_device
      name: "Powermeter ${powermeter_name}"

globals:
  - id: ${powermeter_name}_energy_yesterday_global
    type: float
    restore_value: yes
    
time:
  - platform: homeassistant #sntp
    id: !extend my_time
    on_time:
      - seconds: ${my_second}
        minutes: ${my_minute}
        hours: ${my_hours}
        then:  
          - globals.set:
              id: ${powermeter_name}_energy_yesterday_global
              value: !lambda return ( id(${powermeter_name}_energy_yesterday_global) =  float( id(${powermeter_name}_energy_today).state) );         
    
button:
  - platform: template
    id: ${powermeter_name}_reset_energy
    name: ${name}_${powermeter_name}_reset_energy
    device_id: ${powermeter_name}_device
    on_press:
      then:
        - pzemac.reset_energy: ${powermeter_name}_id
   
sensor:
  - platform: pzemac
    id: ${powermeter_name}_id
    modbus_id: ${powermeter_modbus_id}
    address: ${powermeter_modbus_address}
    current:
      id: ${powermeter_name}_current
      name: ${name}_${powermeter_name}_current
      device_id: ${powermeter_name}_device
      accuracy_decimals: 2
    voltage:
      id: ${powermeter_name}_voltage
      name: ${name}_${powermeter_name}_voltage
      device_id: ${powermeter_name}_device
      accuracy_decimals: 2
    power:
      id: ${powermeter_name}_power
      name: ${name}_${powermeter_name}_power
      device_id: ${powermeter_name}_device
      unit_of_measurement: 'W'
      accuracy_decimals: 1
    frequency:
      id: ${powermeter_name}_frequency
      name: ${name}_${powermeter_name}_frequency
      device_id: ${powermeter_name}_device
      unit_of_measurement: 'Hz'
      accuracy_decimals: 2
    power_factor:
      id: ${powermeter_name}_power_factor
      name: ${name}_${powermeter_name}_power_factor
      device_id: ${powermeter_name}_device
      accuracy_decimals: 2
    energy:
      id: ${powermeter_name}_energy_total
      name: ${name}_${powermeter_name}_energy_total
      device_id: ${powermeter_name}_device
      unit_of_measurement: 'kWh'
      accuracy_decimals: 1
      icon: mdi:counter
      filters: 
        - multiply: 0.001
    update_interval: ${powermeter_update_interval}
    
  - platform: total_daily_energy
    id: ${powermeter_name}_energy_today
    name: ${name}_${powermeter_name}_energy_today
    device_id: ${powermeter_name}_device
    power_id: ${powermeter_name}_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: right
    restore: true
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    id: ${powermeter_name}_energy_yesterday
    name: ${name}_${powermeter_name}_energy_yesterday
    device_id: ${powermeter_name}_device
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:counter
    update_interval: ${powermeter_template_update}
    lambda: |-
      return (id(${powermeter_name}_energy_yesterday).state = id(${powermeter_name}_energy_yesterday_global));
    
  - platform: template
    id: ${powermeter_name}_apparent_power
    name: ${name}_${powermeter_name}_apparent_power
    device_id: ${powermeter_name}_device
    unit_of_measurement: 'VA'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: |-
      if (float(id(${powermeter_name}_power_factor).state) != 0.0){
        return ( (id(${powermeter_name}_power).state/id(${powermeter_name}_power_factor).state));
      }
      else{
        return id(${powermeter_name}_power).state;
      }
    
  - platform: template
    id: ${powermeter_name}__reactive_power
    name: ${name}_${powermeter_name}_reactive_power
    device_id: ${powermeter_name}_device
    unit_of_measurement: 'var'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power

    lambda: return (  id(${powermeter_name}_apparent_power).state*sin(acos( id(${powermeter_name}_power_factor).state ))  );   
