globals:
  - id: ${powermeter_name}_energy_yesteday_global
    type: float
    restore_value: yes
    
time:
  - platform: homeassistant #sntp
    id: my_time
    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        then:  
          - globals.set:
              id: ${powermeter_name}_energy_yesteday_global
              value: !lambda return ( id(${powermeter_name}_energy_yesteday_global) =  float( id(${powermeter_name}_energy_today).state) );         
 
modbus:
   - id: ${powermeter_name}_modbus
     uart_id: ${powermeter_uart_id}
     send_wait_time: ${powermeter_modbus_send_wait_time}
   
button:
  - platform: template
    name: ${name}_${powermeter_name}_reset_energy
    on_press:
      then:
        - pzemac.reset_energy: ${powermeter_name}_pzem
   
   
sensor:
  - platform: pzemac
    id: ${powermeter_name}_pzem
    modbus_id: ${powermeter_name}_modbus
    address: ${powermeter_modbus_address}
    current:
      name: ${name}_${powermeter_name}_current
      accuracy_decimals: 2
    voltage:
      name: ${name}_${powermeter_name}_voltage
      accuracy_decimals: 2
    power:
      name: ${name}_${powermeter_name}_power
      id: ${powermeter_name}_power
      unit_of_measurement: 'W'
      accuracy_decimals: 1
    frequency:
      name: ${name}_${powermeter_name}_frequency
      unit_of_measurement: 'Hz'
      accuracy_decimals: 2
    power_factor:
      name: ${name}_${powermeter_name}_power_factor
      accuracy_decimals: 2
      id: ${powermeter_name}_power_factor
    energy:
      name: ${name}_${powermeter_name}_energy
      unit_of_measurement: 'Wh'
      accuracy_decimals: 1
      id: ${powermeter_name}_energy
    update_interval: ${powermeter_update_interval}

    
  - platform: template
    name: ${name}_${powermeter_name}_energy_total
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: return (( (id(${powermeter_name}_energy).state)/1000.0));
    
  - platform: total_daily_energy
    name: ${name}_${powermeter_name}_energy_today
    id: ${powermeter_name}_energy_today
    power_id: ${powermeter_name}_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: trapezoid
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    name: ${name}_${powermeter_name}_energy_yesteday
    id: ${powermeter_name}_energy_yesteday
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:power
    update_interval: ${powermeter_template_update}
    lambda: |-
      return (id(${powermeter_name}_energy_yesteday).state = id(${powermeter_name}_energy_yesteday_global));
    
  - platform: template
    name: ${name}_${powermeter_name}_apparent_power
    id: ${powermeter_name}_apparent_power
    unit_of_measurement: 'VA'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: |-
      if (float(id(${powermeter_name}_power_factor).state) != 0.0){
        return ( (id(${powermeter_name}_power).state/id(${powermeter_name}_power_factor).state));
      }
      else{
        return id(${powermeter_name}_power).state;
      }
    
  - platform: template
    name: ${name}_${powermeter_name}_reactive_power
    id: ${powermeter_name}__reactive_power
    unit_of_measurement: 'VAr'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: return (  id(${powermeter_name}_apparent_power).state*sin(acos( id(${powermeter_name}_power_factor).state ))  );   
