globals:
  - id: ${powermeter_name}_energy_yesteday_global_${powermeter_sufix}
    type: float
    restore_value: yes
    
time:
  platform: sntp
  id: my_time
  
  on_time:
    - seconds: 59
      minutes: 59
      hours: 23
      then:  
        - globals.set:
                id: ${powermeter_name}_energy_yesteday_global_${powermeter_sufix}
                value: !lambda return ( id(${powermeter_name}_energy_yesteday_global_${powermeter_sufix}) =  float( id(${powermeter_name}_energy_today_${powermeter_sufix}).state) );         
 
modbus:
   - id: ${powermeter_name}_modbus_${powermeter_sufix}
     uart_id: ${powermeter_uart_id}
     send_wait_time: ${powermeter_modbus_send_wait_time}
   
button:
  - platform: template
    name: ${name}_${powermeter_name}_reset_energy_${powermeter_sufix}
    on_press:
      then:
        - pzemac.reset_energy: ${powermeter_name}_pzem_${powermeter_sufix}
   
   
sensor:
  - platform: pzemac
    address: ${powermeter_modbus_address}
    current:
      name: ${name}_${powermeter_name}_current_${powermeter_sufix}
      accuracy_decimals: 2
    voltage:
      name: ${name}_${powermeter_name}_voltage_${powermeter_sufix}
      accuracy_decimals: 2
    power:
      name: ${name}_${powermeter_name}_power_${powermeter_sufix}
      id: ${powermeter_name}_power_${powermeter_sufix}
      unit_of_measurement: 'W'
      accuracy_decimals: 1
    frequency:
      name: ${name}_${powermeter_name}_frequency_${powermeter_sufix}
      unit_of_measurement: 'Hz'
      accuracy_decimals: 2
    power_factor:
      name: ${name}_${powermeter_name}_power_factor_${powermeter_sufix}
      accuracy_decimals: 2
      id: ${powermeter_name}_power_factor_${powermeter_sufix}
    energy:
      name: ${name}_${powermeter_name}_energy_${powermeter_sufix}
      unit_of_measurement: 'Wh'
      accuracy_decimals: 1
      id: ${powermeter_name}_energy_${powermeter_sufix}
    update_interval: ${powermeter_update_interval}
    modbus_id: ${powermeter_name}_modbus_${powermeter_sufix}
    id: ${powermeter_name}_pzem_${powermeter_sufix}
    
  - platform: template
    name: ${name}_${powermeter_name}_energy_total_${powermeter_sufix}
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: return (( (id(${powermeter_name}_energy_${powermeter_sufix}).state)/1000.0));
    
  - platform: total_daily_energy
    name: ${name}_${powermeter_name}_energy_today_${powermeter_sufix}
    id: ${powermeter_name}_energy_today_${powermeter_sufix}
    power_id: ${powermeter_name}_power_${powermeter_sufix}
    unit_of_measurement: 'kWh'
    accuracy_decimals: 2
    method: trapezoid
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    name: ${name}_${powermeter_name}_energy_yesteday_${powermeter_sufix}
    id: ${powermeter_name}_energy_yesteday_${powermeter_sufix}
    unit_of_measurement: 'kWh'
    accuracy_decimals: 2
    icon: mdi:power
    update_interval: ${powermeter_template_update}
    lambda: |-
      return (id(${powermeter_name}_energy_yesteday_${powermeter_sufix}).state = id(${powermeter_name}_energy_yesteday_global_${powermeter_sufix}));
    
  - platform: template
    name: ${name}_${powermeter_name}_apparent_power_${powermeter_sufix}
    id: ${powermeter_name}_apparent_power_${powermeter_sufix}
    unit_of_measurement: 'VA'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: |-
      if (float(id(${powermeter_name}_power_factor_${powermeter_sufix}).state) != 0.0){
        return ( (id(${powermeter_name}_power_${powermeter_sufix}).state/id(${powermeter_name}_power_factor_${powermeter_sufix}).state));
      }
      else{
        return id(${powermeter_name}_power_${powermeter_sufix}).state;
      }
    
  - platform: template
    name: ${name}_${powermeter_name}_reactive_power_${powermeter_sufix}
    id: ${powermeter_name}__reactive_power_${powermeter_sufix}
    unit_of_measurement: 'VAr'
    accuracy_decimals: 1
    update_interval: ${powermeter_template_update}
    icon: mdi:power
    lambda: return (  id(${powermeter_name}_apparent_power_${powermeter_sufix}).state*sin(acos( id(${powermeter_name}_power_factor_${powermeter_sufix}).state ))  );   