sensor:
  - platform: bmp280
    temperature:
      name: ${name}_${environnemental_name}_temperature
      accuracy_decimals: 1
      oversampling: 16x
      id: ${environnemental_name}_temperature
    pressure:
      name: ${name}_${environnemental_name}_pression
      accuracy_decimals: 1
      id: ${environnemental_name}_pression
    address: ${environnemental_address}
    update_interval: ${environnemental_update_interval}
    i2c_id: ${environnemental_i2c_bus}
