modbus_controller:
  - id: ${inverter_name}_modbus_controller
    address: ${inverter_modbus_address}
    modbus_id: ${inverter_modbus_id}
    command_throttle: ${inverter_modbus_throttle}
    setup_priority: -10
    update_interval: ${inverter_update_interval}
    
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_state
    id: ${inverter_name}_state
    address: 0x0404
    response_size: 2
    register_type: holding
    icon: 'mdi:information-outline'
    raw_encode: HEXBYTES
    lambda: |-
      auto z = "Unknown";
      char value = data[item->offset+1];
      switch (value) {
        case 0: return std::string("Waiting");
        case 1: return std::string("Production check");
        case 2: return std::string("Production");
        case 3: return std::string("Fault");
        case 4: return std::string("Permanent");
        case 5: return std::string("EPS");
        case 6: return std::string("fault");
        case 7: return std::string("permanent fault");
        default: return std::string("Unknown");
      }
      return x;
      
sensor:

  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_inverter_temperature
    id: ${inverter_name}_inverter_temperature
    register_type: holding
    address: 0x0418
    unit_of_measurement: '°C'
    state_class: 'measurement'
    device_class: 'temperature'
    icon: 'mdi:temperature-celsius'
    value_type: U_WORD
      
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_temperature
    id: ${inverter_name}_temperature
    register_type: holding
    address: 0x041A
    unit_of_measurement: '°C'
    state_class: 'measurement'
    device_class: 'temperature'
    icon: 'mdi:temperature-celsius'
    value_type: U_WORD
   
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_energy_today_duration
    id: ${inverter_name}_ac_output_energy_today_duration
    register_type: holding
    address: 0x0426
    unit_of_measurement: 'min'
    icon: 'mdi:timeline-clock'
    value_type: U_WORD
      
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_energy_total_duration
    id: ${inverter_name}_ac_output_energy_total_duration
    register_type: holding
    address: 0x0427
    unit_of_measurement: 'min'
    icon: 'mdi:timeline-clock'
    value_type: U_DWORD
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_isolation_resistance
    id: ${inverter_name}_pv_isolation_resistance
    register_type: holding
    address: 0x042B
    unit_of_measurement: 'Ohm'
    state_class: 'measurement'
    icon: 'mdi:omega'
    value_type: U_WORD
        
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_frequency
    id: ${inverter_name}_ac_output_frequency
    register_type: holding
    address: 0x0484                
    unit_of_measurement: 'Hz'
    state_class: 'measurement'
    icon: 'mdi:current-ac'
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_power
    id: ${inverter_name}_ac_output_power
    register_type: holding
    address: 0x0485
    unit_of_measurement: 'W'
    state_class: 'measurement'
    device_class: 'power'
    icon: 'mdi:solar-power-variant-outline'
    value_type: U_WORD
    filters:
      - multiply: 10
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_reactive_power
    id: ${inverter_name}_ac_output_reactive_power
    register_type: holding
    address: 0x0487  
    unit_of_measurement: 'kVar'
    state_class: 'measurement'
    icon: 'mdi:math-cos'
    value_type: S_WORD
    filters:
      - multiply: 10
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_voltage
    id: ${inverter_name}_ac_output_voltage
    register_type: holding
    address: 0x048D
    unit_of_measurement: 'V'
    state_class: 'measurement'
    device_class: 'voltage'
    icon: 'mdi:alpha-v-circle'
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_ac_output_current
    id: ${inverter_name}_ac_output_current
    register_type: holding
    address: 0x048E
    unit_of_measurement: 'A'
    state_class: 'measurement'
    device_class: 'current'
    icon: 'mdi:alpha-a-circle'
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

    
    ################################# PV  ####################""
    
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_voltage
    id: ${inverter_name}_pv_voltage
    register_type: holding
    address: 0x0584 
    unit_of_measurement: 'V'
    state_class: 'measurement'
    device_class: 'voltage'
    icon: 'mdi:alpha-v-circle-outline'
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_current
    id: _${inverter_name}_pv_current
    register_type: holding
    address: 0x0585 
    unit_of_measurement: 'A'
    state_class: 'measurement'
    device_class: 'current'
    icon: 'mdi:alpha-a-circle-outline'
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
 
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_power
    id: ${inverter_name}_pv_power
    register_type: holding
    address: 0x0586 
    unit_of_measurement: 'W'
    state_class: 'measurement'
    device_class: 'power'
    icon: 'mdi:solar-power'
    value_type: U_WORD
    filters:
      - multiply: 10    
    
  ########################### Statistics & internal data ################
  
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_energy_today
    id: ${inverter_name}_pv_energy_today
    register_type: holding
    address: 0x0685
    unit_of_measurement: 'kWh'
    state_class: 'measurement'
    device_class: 'energy'
    icon: 'mdi:solar-power-variant-outline'
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01  
      
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_pv_energy_total
    id: ${inverter_name}_pv_energy_total
    register_type: holding
    address: 0x0686    
    unit_of_measurement: 'kWh'
    accuracy_decimals: 2
    device_class: 'energy'
    state_class: 'total_increasing'
    icon: 'mdi:solar-power-variant-outline'
    value_type: U_DWORD
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.1
  
  - platform: modbus_controller
    modbus_controller_id: ${inverter_name}_modbus_controller
    name: ${name}_${inverter_name}_bus_voltage
    id: ${inverter_name}_bus_voltage
    register_type: holding
    address: 0x06CC      
    unit_of_measurement: 'V'
    state_class: 'measurement'
    device_class: 'voltage'
    icon: 'mdi:alpha-v-circle-outline'
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1