#    _______ __   ____  _ __      __
#   / ____(_) /  / __ \(_) /___  / /____
#  / /_  / / /  / /_/ / / / __ \/ __/ _ \
# / __/ / / /  / ____/ / / /_/ / /_/  __/
#/_/   /_/_/  /_/   /_/_/\____/\__/\___/

# Updated : 2026.06.15
# Version : 1.0.1
# GitHub  : https://github.com/Dackara/

esphome:
  on_boot:
    priority: -100.0
    then:
      - select.set:
          id: ${fpilote_id}_${fpilote_mode}
          option: ${fpilote_initial_option}

output:
  - platform: gpio
    id: ${fpilote_hub}_output_${fpilote_pos_pin}
    pin:
      sx1509: ${fpilote_hub}
      number: ${fpilote_pos_pin}
      mode:
        output: true
      inverted: false
    
  - platform: gpio
    id: ${fpilote_hub}_output_${fpilote_neg_pin}
    pin:
      sx1509: ${fpilote_hub}
      number: ${fpilote_neg_pin}
      mode:
        output: true
      inverted: false
    
switch:
  - platform: output
    id: ${fpilote_id}_${fpilote_pos_pin}
    name: '${name}_${fpilote_id}_${fpilote_pos_pin}'
    device_id: fil_pilote_device
    output: ${fpilote_hub}_output_${fpilote_pos_pin}
    disabled_by_default: true
    entity_category: diagnostic
      
  - platform: output
    id: ${fpilote_id}_${fpilote_neg_pin}
    name: '${name}_${fpilote_id}_${fpilote_neg_pin}'
    device_id: fil_pilote_device
    output: ${fpilote_hub}_output_${fpilote_neg_pin}
    disabled_by_default: true
    entity_category: diagnostic
    
select:
  - platform: template
    id: ${fpilote_id}_${fpilote_mode}
    name: "${name}_${fpilote_id}_${fpilote_mode}"
    device_id: fil_pilote_device
    options:
     - "Confort"    #Pas de signal envoyé
     - "Eco"        #Alternance pleine
     - "Hors-gel"   #Alternance négative
     - "Arrêt"      #Alternance positive
     - "Confort -1" #Alternance pleine temporisé (4'57"off/3"on/..)
     - "Confort -2" #Alternance pleine temporisé (4'53"off/7"on/..)
    initial_option: ${fpilote_initial_option}
    optimistic: true
    icon: mdi:radiator
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]
       
    on_value:
      then:

        - if:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Confort";
            then:
              - switch.turn_off: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_off: ${fpilote_id}_${fpilote_neg_pin}

        - if:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Eco";
            then:
              - switch.turn_on: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_on: ${fpilote_id}_${fpilote_neg_pin}

        - if:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Hors-gel";
            then:
              - switch.turn_on: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_off: ${fpilote_id}_${fpilote_neg_pin}

        - if:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Arrêt";
            then:
              - switch.turn_off: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_on: ${fpilote_id}_${fpilote_neg_pin}

        - while:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Confort -1";
            then:
              - switch.turn_on: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_on: ${fpilote_id}_${fpilote_neg_pin}

              - wait_until:
                  timeout: 3s
                  condition:
                    lambda: |-
                      return id(${fpilote_id}_${fpilote_mode}).current_option() != "Confort -1";

              - switch.turn_off: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_off: ${fpilote_id}_${fpilote_neg_pin}

              - wait_until:
                  timeout: 297s
                  condition:
                    lambda: |-
                      return id(${fpilote_id}_${fpilote_mode}).current_option() != "Confort -1";

        - while:
            condition:
              lambda: |-
                return id(${fpilote_id}_${fpilote_mode}).current_option() == "Confort -2";
            then:
              - switch.turn_on: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_on: ${fpilote_id}_${fpilote_neg_pin}

              - wait_until:
                  timeout: 7s
                  condition:
                    lambda: |-
                      return id(${fpilote_id}_${fpilote_mode}).current_option() != "Confort -2";

              - switch.turn_off: ${fpilote_id}_${fpilote_pos_pin}
              - switch.turn_off: ${fpilote_id}_${fpilote_neg_pin}

              - wait_until:
                  timeout: 293s
                  condition:
                    lambda: |-
                      return id(${fpilote_id}_${fpilote_mode}).current_option() != "Confort -2";