external_components:
  - source: github://dackara/esphome-pylontech@mos_st
    refresh: 0s

pylontech:
  id: ${pylon_id}
  uart_id: ${pylon_uart_id}
  update_interval: ${pylon_update_interval}

sensor:
  - platform: pylontech
    pylontech_id: ${pylon_id}
    battery: ${pylon_number}
    voltage:
      id: ${pylon_id}${pylon_number}_tension
      name: '${pylon_name}${pylon_number}_tension'
    current:
      id: ${pylon_id}${pylon_number}_courant_charge
      name: '${pylon_name}${pylon_number}_courant_charge'
    coulomb:
      id: ${pylon_id}${pylon_number}_capacity
      name: '${pylon_name}${pylon_number}_capacity'
    temperature:
      id: ${pylon_id}${pylon_number}_temperature
      name: '${pylon_name}${pylon_number}_temperature'
    temperature_low:
      id: ${pylon_id}${pylon_number}_low_temperature
      name: '${pylon_name}${pylon_number} low temperature'
    temperature_high:
      id: ${pylon_id}${pylon_number}_high_temperature
      name: '${pylon_name}${pylon_number} high temperature'
    voltage_low:
      id: ${pylon_id}${pylon_number}_cell_low
      name: '${pylon_name}${pylon_number}_cell_low'
    voltage_high:
      id: ${pylon_id}${pylon_number}_cell_high
      name: '${pylon_name}${pylon_number}_cell_high'  
    mos_temperature:
      id: ${pylon_id}${pylon_number}_mosfet_temperature
      name: '${pylon_name}${pylon_number}_mosfet_temperature'
      
text_sensor:
  - platform: pylontech
    pylontech_id: ${pylon_id}
    battery: ${pylon_number}
    base_state:
      id: ${pylon_id}${pylon_number}_base_state
      name: '${pylon_name} ${pylon_number} Base State'
    voltage_state:
      id: ${pylon_id}${pylon_number}_voltage_state
      name: '${pylon_name} ${pylon_number} voltage sate'
    current_state:
      id: ${pylon_id}${pylon_number}_current_state
      name: '${pylon_name} ${pylon_number} current state'
    temperature_state:
      id: ${pylon_id}${pylon_number}_temperature_state
      name: '${pylon_name} ${pylon_number} temperature state'
    date_state:
      id: ${pylon_id}${pylon_number}_date_state
      name: '${pylon_name} ${pylon_number} date state'
    time_state:
      id: ${pylon_id}${pylon_number}_time_state
      name: '${pylon_name} ${pylon_number} time state'
    bv_state:
      id: ${pylon_id}${pylon_number}_bv_state
      name: '${pylon_name} ${pylon_number} bv state'
    bt_state:
      id: ${pylon_id}${pylon_number}_bt_state
      name: '${pylon_name} ${pylon_number} bt state'
    mos_state:
      id: ${pylon_id}${pylon_number}_mos_state
      name: '${pylon_name} ${pylon_number} mos state' 