# Updated : 2026.06.15
# Version : 1.0.4
# GitHub  : https://github.com/SeByDocKy/pvbrain2

sensor:
  - platform: dallas_temp
    id: ${environnemental_name}
    name: ${name}_${environnemental_name}
    device_id: one_wire_dallas_device
    one_wire_id: one_wire_hub
    address: ${environnemental_address}
    update_interval: ${environnemental_update_interval}
    filters:
      - filter_out: 85
      - filter_out: 128
      - filter_out: NAN
      - clamp:
         min_value: -20
         max_value: 100
         ignore_out_of_range: true
