sensor:
  - platform: dallas
    name: ${name}_${environnemental_name}
    id: ${environnemental_name} 
    address: ${environnemental_address}
    update_interval: ${environnemental_update_interval}
