external_components:
  - source: github://syssi/esphome-seplos-bms@main
    refresh: 0s

seplos_modbus:
  - id: ${bms_name}_seplos_modbus_${bms_sufix}
    uart_id: ${bms_uart_id}
    rx_timeout: ${bms_rx_timeout}
  
seplos_bms:
  - id: ${bms_name}_seplos_bms_${bms_sufix}
  # Dip switch configuration of a single pack setup / address 0x0
  #  8    7    6    5    4    3    2    1
  # off, off, off, off, off, off, off, off
    address: ${bms_modbus_address}
  # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: ${bms_protocol} 
    seplos_modbus_id: ${bms_name}_seplos_modbus_${bms_sufix}
    update_interval: ${bms_update_interval}
    
sensor:
  - platform: seplos_bms
    seplos_bms_id: ${bms_name}_seplos_bms_${bms_sufix}
    min_cell_voltage:
      name: ${name}_${bms_name}_min_cell_voltage_${bms_sufix}
    max_cell_voltage:
      name: ${name}_${bms_name}_max_cell_voltage_${bms_sufix}
    min_voltage_cell:
      name: ${name}_${bms_name}_min_voltage_cell_${bms_sufix}
    max_voltage_cell:
      name: ${name}_${bms_name}_max_voltage_cell_${bms_sufix}
    delta_cell_voltage:
      name: ${name}_${bms_name}_delta_cell_voltage_${bms_sufix}
    average_cell_voltage:
      name: ${name}_${bms_name}_average_cell_voltage_${bms_sufix}
    cell_voltage_1:
      name: ${name}_${bms_name}_cell_voltage_1_${bms_sufix}
    cell_voltage_2:
      name: ${name}_${bms_name}_cell_voltage_2_${bms_sufix}
    cell_voltage_3:
      name: ${name}_${bms_name}_cell_voltage_3_${bms_sufix}
    cell_voltage_4:
      name: ${name}_${bms_name}_cell_voltage_4_${bms_sufix}
    cell_voltage_5:
      name: ${name}_${bms_name}_cell_voltage_5_${bms_sufix}
    cell_voltage_6:
      name: ${name}_${bms_name}_cell_voltage_6_${bms_sufix}
    cell_voltage_7:
      name: ${name}_${bms_name}_cell_voltage_7_${bms_sufix}
    cell_voltage_8:
      name: ${name}_${bms_name}_cell_voltage_8_${bms_sufix}
    cell_voltage_9:
      name: ${name}_${bms_name}_cell_voltage_9_${bms_sufix}
    cell_voltage_10:
      name: ${name}_${bms_name}_cell_voltage_10_${bms_sufix}
    cell_voltage_11:
      name: ${name}_${bms_name}_cell_voltage_11_${bms_sufix}
    cell_voltage_12:
      name: ${name}_${bms_name}_cell_voltage_12_${bms_sufix}
    cell_voltage_13:
      name: ${name}_${bms_name}_cell_voltage_13_${bms_sufix}
    cell_voltage_14:
      name: ${name}_${bms_name}_cell_voltage_14_${bms_sufix}
    cell_voltage_15:
      name: ${name}_${bms_name}_cell_voltage_15_${bms_sufix}
    cell_voltage_16:
      name: ${name}_${bms_name}_cell_voltage_16_${bms_sufix}
    temperature_1:
      name: ${name}_${bms_name}_temperature_1_${bms_sufix}
    temperature_2:
      name: ${name}_${bms_name}_temperature_2_${bms_sufix}
    temperature_3:
      name: ${name}_${bms_name}_temperature_3_${bms_sufix}
    temperature_4:
      name: ${name}_${bms_name}_temperature_4_${bms_sufix}
    temperature_5:
      name: ${name}_${bms_name}_environment_temperature_${bms_sufix}
    temperature_6:
      name: ${name}_${bms_name}_mosfet_temperature_${bms_sufix}
    total_voltage:
      name: ${name}_${bms_name}_battery_voltage_${bms_sufix}
    current:
      name: ${name}_${bms_name}_battery_current_${bms_sufix}
    power:
      name: ${name}_${bms_name}_battery_power_${bms_sufix}
    charging_power:
      name: ${name}_${bms_name}_battery_charging power_${bms_sufix}
    discharging_power:
      name: ${name}_${bms_name}_battery_discharging power_${bms_sufix}
    residual_capacity:
      name: ${name}_${bms_name}_battery_residual capacity_${bms_sufix}
    battery_capacity:
      name: ${name}_${bms_name}_battery_capacity_${bms_sufix}
    rated_capacity:
      name: ${name}_${bms_name}_battery_rated capacity_${bms_sufix}
    state_of_charge:
      name: ${name}_${bms_name}_soc_${bms_sufix}
    charging_cycles:
      name: ${name}_${bms_name}_charging_cycles_${bms_sufix}
    state_of_health:
      name: ${name}_${bms_name}_soh_${bms_sufix}
    port_voltage:
      name: ${name}_${bms_name}_port_voltage_${bms_sufix}