external_components:
  - source: github://syssi/esphome-seplos-bms@main
    refresh: 0s

seplos_modbus:
  - id: ${bms_name}_seplos_modbus
    uart_id: ${bms_uart_id}
    rx_timeout: ${bms_rx_timeout}
  
seplos_bms:
  - id: ${bms_name}_seplos_bms
  # Dip switch configuration of a single pack setup / address 0x0
  #  8    7    6    5    4    3    2    1
  # off, off, off, off, off, off, off, off
    address: ${bms_modbus_address}
  # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: ${bms_protocol} 
    seplos_modbus_id: ${bms_name}_seplos_modbus
    update_interval: ${bms_update_interval}
    
sensor:
  - platform: seplos_bms
    seplos_bms_id: ${bms_name}_seplos_bms
    min_cell_voltage:
      name: ${name}_${bms_name}_min_cell_voltage
    max_cell_voltage:
      name: ${name}_${bms_name}_max_cell_voltage
    min_voltage_cell:
      name: ${name}_${bms_name}_min_voltage_cell
    max_voltage_cell:
      name: ${name}_${bms_name}_max_voltage_cell
    delta_cell_voltage:
      name: ${name}_${bms_name}_delta_cell_voltage
    average_cell_voltage:
      name: ${name}_${bms_name}_average_cell_voltage
    cell_voltage_1:
      name: ${name}_${bms_name}_cell_voltage_1
    cell_voltage_2:
      name: ${name}_${bms_name}_cell_voltage_2
    cell_voltage_3:
      name: ${name}_${bms_name}_cell_voltage_3
    cell_voltage_4:
      name: ${name}_${bms_name}_cell_voltage_4
    cell_voltage_5:
      name: ${name}_${bms_name}_cell_voltage_5
    cell_voltage_6:
      name: ${name}_${bms_name}_cell_voltage_6
    cell_voltage_7:
      name: ${name}_${bms_name}_cell_voltage_7
    cell_voltage_8:
      name: ${name}_${bms_name}_cell_voltage_8
    cell_voltage_9:
      name: ${name}_${bms_name}_cell_voltage_9
    cell_voltage_10:
      name: ${name}_${bms_name}_cell_voltage_10
    cell_voltage_11:
      name: ${name}_${bms_name}_cell_voltage_11
    cell_voltage_12:
      name: ${name}_${bms_name}_cell_voltage_12
    cell_voltage_13:
      name: ${name}_${bms_name}_cell_voltage_13
    cell_voltage_14:
      name: ${name}_${bms_name}_cell_voltage_14
    cell_voltage_15:
      name: ${name}_${bms_name}_cell_voltage_15
    cell_voltage_16:
      name: ${name}_${bms_name}_cell_voltage_16
    temperature_1:
      name: ${name}_${bms_name}_temperature_1
    temperature_2:
      name: ${name}_${bms_name}_temperature_2
    temperature_3:
      name: ${name}_${bms_name}_temperature_3
    temperature_4:
      name: ${name}_${bms_name}_temperature_4
    temperature_5:
      name: ${name}_${bms_name}_environment_temperature
    temperature_6:
      name: ${name}_${bms_name}_mosfet_temperature
    total_voltage:
      name: ${name}_${bms_name}_battery_voltage
    current:
      name: ${name}_${bms_name}_battery_current
    power:
      name: ${name}_${bms_name}_battery_power
    charging_power:
      name: ${name}_${bms_name}_battery_charging power
    discharging_power:
      name: ${name}_${bms_name}_battery_discharging power
    residual_capacity:
      name: ${name}_${bms_name}_battery_residual capacity
    battery_capacity:
      name: ${name}_${bms_name}_battery_capacity
    rated_capacity:
      name: ${name}_${bms_name}_battery_rated capacity
    state_of_charge:
      name: ${name}_${bms_name}_soc
    charging_cycles:
      name: ${name}_${bms_name}_charging_cycles
    state_of_health:
      name: ${name}_${bms_name}_soh
    port_voltage:
      name: ${name}_${bms_name}_port_voltage