sensor:
  - platform: template
    id: ${relative_error_name}_relative_error
    name: ${name}_${relative_error_name}_relative_error
    accuracy_decimals: 1
    icon: mdi:percent
    unit_of_measurement: '%'
    update_interval: ${relative_error_template_update}
    lambda: |-
      if (id(${relative_error_source1}).state != 0.0){
        return (100.0f*fabs(id(${relative_error_source1}).state - id(${relative_error_source2}).state)/fabs(id(${relative_error_source1}).state));
      }
      else{
        return 0.0f;
      }