# Updated : 2024.05.20
# Version : 1.0.0
# GitHub  : https://github.com/Dackara/

binary_sensor:
  - platform: gpio
    id: ${weikai_name}_output_pin_0
    name: ${name}_${weikai_name}_output_pin_0
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 0
      mode:
        input: true
      inverted: ${weikai_inverted_pin0} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_1
    name: ${name}_${weikai_name}_output_pin_1
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 1
      mode:
        input: true
      inverted: ${weikai_inverted_pin1} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_2
    name: ${name}_${weikai_name}_output_pin_2
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 2
      mode:
        input: true
      inverted: ${weikai_inverted_pin2} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_3
    name: ${name}_${weikai_name}_output_pin_3
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 3
      mode:
        input: true
      inverted: ${weikai_inverted_pin3} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_4
    name: ${name}_${weikai_name}_output_pin_4
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 4
      mode:
        input: true
      inverted: ${weikai_inverted_pin4} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_5
    name: ${name}_${weikai_name}_output_pin_5
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 5
      mode:
        input: true
      inverted: ${weikai_inverted_pin5} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_6
    name: ${name}_${weikai_name}_output_pin_6
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 6
      mode:
        input: true
      inverted: ${weikai_inverted_pin6} #false
  - platform: gpio
    id: ${weikai_name}_output_pin_7
    name: ${name}_${weikai_name}_output_pin_7
    pin:
      wk2168_spi: ${weikai_id} #uart_bridge0
      number: 7
      mode:
        input: true
      inverted: ${weikai_inverted_pin7} #false