# Updated : 2026.06.16
# Version : 1.0.1
# GitHub  : https://github.com/Dackara/

esphome:
  devices:
    - id: ${relays_name}_device
      name: "GPIO ${relays_name}"

output:
  - platform: gpio
    id: ${relays_name}_output_pin0
    pin:
      sx1509: ${relays_hub}
      number: 0
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: ${relays_name}_output_pin1
    pin:
      sx1509: ${relays_hub}
      number: 1
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: ${relays_name}_output_pin2
    pin:
      sx1509: ${relays_hub}
      number: 2
      mode:
        output: true
      inverted: true
 
  - platform: gpio
    id: ${relays_name}_output_pin3
    pin:
      sx1509: ${relays_hub}
      number: 3
      mode:
        output: true
      inverted: true 

  - platform: gpio
    id: ${relays_name}_output_pin4
    pin:
      sx1509: ${relays_hub}
      number: 4
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin5
    pin:
      sx1509: ${relays_hub}
      number: 5
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin6
    pin:
      sx1509: ${relays_hub}
      number: 6
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin7
    pin:
      sx1509: ${relays_hub}
      number: 7
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin8
    pin:
      sx1509: ${relays_hub}
      number: 8
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin9
    pin:
      sx1509: ${relays_hub}
      number: 9
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin10
    pin:
      sx1509: ${relays_hub}
      number: 10
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin11
    pin:
      sx1509: ${relays_hub}
      number: 11
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin12
    pin:
      sx1509: ${relays_hub}
      number: 12
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin13
    pin:
      sx1509: ${relays_hub}
      number: 13
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin14
    pin:
      sx1509: ${relays_hub}
      number: 14
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: ${relays_name}_output_pin15
    pin:
      sx1509: ${relays_hub}
      number: 15
      mode:
        output: true
      inverted: true
       
switch:
  - platform: output
    id: ${relays_name}_switch_pin0
    name: ${name}_${relays_name}_switch_pin0
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin0
    
  - platform: output
    id: ${relays_name}_switch_pin1
    name: ${name}_${relays_name}_switch_pin1
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin1  
  
  - platform: output
    id: ${relays_name}_switch_pin2
    name: ${name}_${relays_name}_switch_pin2
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin2

  - platform: output
    id: ${relays_name}_switch_pin3
    name: ${name}_${relays_name}_switch_pin3
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin3

  - platform: output
    id: ${relays_name}_switch_pin4
    name: ${name}_${relays_name}_switch_pin4
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin4

  - platform: output
    id: ${relays_name}_switch_pin5
    name: ${name}_${relays_name}_switch_pin5
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin5

  - platform: output
    id: ${relays_name}_switch_pin6
    name: ${name}_${relays_name}_switch_pin6
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin6

  - platform: output
    id: ${relays_name}_switch_pin7
    name: ${name}_${relays_name}_switch_pin7
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin7    

  - platform: output
    id: ${relays_name}_switch_pin8
    name: ${name}_${relays_name}_switch_pin8
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin8

  - platform: output
    id: ${relays_name}_switch_pin9
    name: ${name}_${relays_name}_switch_pin9
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin9

  - platform: output
    id: ${relays_name}_switch_pin10
    name: ${name}_${relays_name}_switch_pin10
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin10

  - platform: output
    id: ${relays_name}_switch_pin11
    name: ${name}_${relays_name}_switch_pin11
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin11

  - platform: output
    id: ${relays_name}_switch_pin12
    name: ${name}_${relays_name}_switch_pin12
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin12

  - platform: output
    id: ${relays_name}_switch_pin13
    name: ${name}_${relays_name}_switch_pin13
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin13

  - platform: output
    id: ${relays_name}_switch_pin14
    name: ${name}_${relays_name}_switch_pin14
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin14

  - platform: output
    id: ${relays_name}_switch_pin15
    name: ${name}_${relays_name}_switch_pin15
    device_id: ${relays_name}_device
    output: ${relays_name}_output_pin15   